name : pull-request-workflow 1
on : pull_request

jobs :
  pull-request-job :
    runs-on : ubuntu-latest
    steps :
      - name : step 1
        run : echo "This is pull request workflow"
      - name : step 2
        run : |
          echo "This is pull request workflow - step 2"
          echo "Running multiple commands"
